let area = [{
  'label': '全市',
  'value': 'SHJCK01000'
}, {
  'label': '崇明区',
  'value': 'SHJCK01019'
}, {
  'label': '松江区',
  'value': 'SHJCK01018'
}, {
  'label': '青浦区',
  'value': 'SHJCK01017'
}, {
  'label': '虹口区',
  'value': 'SHJCK01001'
}, {
  'label': '奉贤区',
  'value': 'SHJCK01015'
}, {
  'label': '浦东新区',
  'value': 'SHJCK01014030'
}, {
  'label': '嘉定区',
  'value': 'SHJCK01013'
}, {
  'label': '闵行区',
  'value': 'SHJCK01012'
}, {
  'label': '宝山区',
  'value': 'SHJCK01011'
}, {
  'label': '金山区',
  'value': 'SHJCK01010'
}, {
  'label': '静安区',
  'value': 'SHJCK01009'
}, {
  'label': '长宁区',
  'value': 'SHJCK01008'
}, {
  'label': '普陀区',
  'value': 'SHJCK01006'
}, {
  'label': '徐汇区',
  'value': 'SHJCK01005'
}, {
  'label': '闸北区',
  'value': 'SHJCK01004'
}, {
  'label': '杨浦区',
  'value': 'SHJCK01003'
}, {
  'label': '黄埔区',
  'value': 'SHJCK01002'
}]
let caseType = [{
  'label': '民事',
  'value': '民事'
}, {
  'label': '刑事',
  'value': '刑事'
}, {
  'label': '治安',
  'value': '治安'
}, {
  'label': '房产',
  'value': '房产'
}, {
  'label': '医患',
  'value': '医患'
}, {
  'label': '交通',
  'value': '交通'
}, {
  'label': '劳动',
  'value': '劳动'
}, {
  'label': '涉校',
  'value': '涉校'
}, {
  'label': '知产',
  'value': '知产'
}]

let businessType = [{
  'label': '人民调解',
  'value': '人民调解'
}, {
  'label': '110联动',
  'value': '110联动'
}, {
  'label': '公共法律服务',
  'value': '公共法律服务'
}, {
  'label': '纠纷排查',
  'value': '纠纷排查'
}]
export default {area, caseType, businessType}
